//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TieuChuanWebVer4.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class bang1_final
    {
        public string A { get; set; }
        public string B { get; set; }
        public System.Guid id { get; set; }
    }
}
