//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TieuChuanWebVer4.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class dm_bomon
    {
        public System.Guid id { get; set; }
        public string mabomon { get; set; }
        public string tenbomon { get; set; }
        public string makhoa { get; set; }
        public string googledrive { get; set; }
    }
}
