//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TieuChuanWebVer4.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class dm_tieuchuan
    {
        public System.Guid id { get; set; }
        public string ma_tieuchuan { get; set; }
        public string ten_tieuchuan { get; set; }
        public string ghichu { get; set; }
        public string nguoitao { get; set; }
        public Nullable<System.DateTime> ngaytao { get; set; }
        public string nguoisua { get; set; }
        public Nullable<System.DateTime> ngaysua { get; set; }
        public string noidung { get; set; }
        public byte[] noidungbyte { get; set; }
    }
}
