//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TieuChuanWebVer4.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ht_nsd_form
    {
        public System.Guid id { get; set; }
        public string ma_nsd { get; set; }
        public string ma_form { get; set; }
        public Nullable<bool> them { get; set; }
        public Nullable<bool> xoa { get; set; }
        public Nullable<bool> sua { get; set; }
        public Nullable<bool> xem { get; set; }
        public Nullable<bool> @in { get; set; }
        public string ten_form { get; set; }
        public string ma_nhom { get; set; }
    }
}
