//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TieuChuanWebVer4.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class QL_TieuChuan2Entities : DbContext
    {
        public QL_TieuChuan2Entities()
            : base("name=QL_TieuChuan2Entities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<bang1_final> bang1_final { get; set; }
        public virtual DbSet<dm_bomon> dm_bomon { get; set; }
        public virtual DbSet<dm_dinhdanh> dm_dinhdanh { get; set; }
        public virtual DbSet<dm_khoa> dm_khoa { get; set; }
        public virtual DbSet<dm_tieuchi> dm_tieuchi { get; set; }
        public virtual DbSet<dm_tieuchuan> dm_tieuchuan { get; set; }
        public virtual DbSet<hs_noidung> hs_noidung { get; set; }
        public virtual DbSet<hs_taptinct> hs_taptinct { get; set; }
        public virtual DbSet<hs_tapting> hs_tapting { get; set; }
        public virtual DbSet<ht_dm_form> ht_dm_form { get; set; }
        public virtual DbSet<ht_dm_menu> ht_dm_menu { get; set; }
        public virtual DbSet<ht_dm_nsd> ht_dm_nsd { get; set; }
        public virtual DbSet<ht_nsd_form> ht_nsd_form { get; set; }
        public virtual DbSet<ht_nsd_menu> ht_nsd_menu { get; set; }
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
    
        [DbFunction("QL_TieuChuan2Entities", "LayBangTheoCot")]
        public virtual IQueryable<LayBangTheoCot_Result> LayBangTheoCot(string column_name, string table_name)
        {
            var column_nameParameter = column_name != null ?
                new ObjectParameter("column_name", column_name) :
                new ObjectParameter("column_name", typeof(string));
    
            var table_nameParameter = table_name != null ?
                new ObjectParameter("table_name", table_name) :
                new ObjectParameter("table_name", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.CreateQuery<LayBangTheoCot_Result>("[QL_TieuChuan2Entities].[LayBangTheoCot](@column_name, @table_name)", column_nameParameter, table_nameParameter);
        }
    
        [DbFunction("QL_TieuChuan2Entities", "Split")]
        public virtual IQueryable<Split_Result> Split(string @string, string delimiter)
        {
            var stringParameter = @string != null ?
                new ObjectParameter("String", @string) :
                new ObjectParameter("String", typeof(string));
    
            var delimiterParameter = delimiter != null ?
                new ObjectParameter("Delimiter", delimiter) :
                new ObjectParameter("Delimiter", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.CreateQuery<Split_Result>("[QL_TieuChuan2Entities].[Split](@String, @Delimiter)", stringParameter, delimiterParameter);
        }
    
        public virtual int cn_CongNoTongHop(string matk, Nullable<System.DateTime> tungay, Nullable<System.DateTime> denngay, string tableTemp, Nullable<bool> loai, Nullable<bool> noibo)
        {
            var matkParameter = matk != null ?
                new ObjectParameter("matk", matk) :
                new ObjectParameter("matk", typeof(string));
    
            var tungayParameter = tungay.HasValue ?
                new ObjectParameter("tungay", tungay) :
                new ObjectParameter("tungay", typeof(System.DateTime));
    
            var denngayParameter = denngay.HasValue ?
                new ObjectParameter("denngay", denngay) :
                new ObjectParameter("denngay", typeof(System.DateTime));
    
            var tableTempParameter = tableTemp != null ?
                new ObjectParameter("tableTemp", tableTemp) :
                new ObjectParameter("tableTemp", typeof(string));
    
            var loaiParameter = loai.HasValue ?
                new ObjectParameter("loai", loai) :
                new ObjectParameter("loai", typeof(bool));
    
            var noiboParameter = noibo.HasValue ?
                new ObjectParameter("noibo", noibo) :
                new ObjectParameter("noibo", typeof(bool));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("cn_CongNoTongHop", matkParameter, tungayParameter, denngayParameter, tableTempParameter, loaiParameter, noiboParameter);
        }
    
        public virtual int cn_CongNoTongHopChiTiet(string maBp, string maHh, string maKh, string loaiNte, string ma_dv, Nullable<decimal> dkno, Nullable<decimal> dkco, Nullable<decimal> ckno, Nullable<decimal> ckco, Nullable<decimal> dkno_nt, Nullable<decimal> dkco_nt, Nullable<decimal> ckno_nt, Nullable<decimal> ckco_nt, string tableTemp)
        {
            var maBpParameter = maBp != null ?
                new ObjectParameter("maBp", maBp) :
                new ObjectParameter("maBp", typeof(string));
    
            var maHhParameter = maHh != null ?
                new ObjectParameter("maHh", maHh) :
                new ObjectParameter("maHh", typeof(string));
    
            var maKhParameter = maKh != null ?
                new ObjectParameter("maKh", maKh) :
                new ObjectParameter("maKh", typeof(string));
    
            var loaiNteParameter = loaiNte != null ?
                new ObjectParameter("loaiNte", loaiNte) :
                new ObjectParameter("loaiNte", typeof(string));
    
            var ma_dvParameter = ma_dv != null ?
                new ObjectParameter("ma_dv", ma_dv) :
                new ObjectParameter("ma_dv", typeof(string));
    
            var dknoParameter = dkno.HasValue ?
                new ObjectParameter("dkno", dkno) :
                new ObjectParameter("dkno", typeof(decimal));
    
            var dkcoParameter = dkco.HasValue ?
                new ObjectParameter("dkco", dkco) :
                new ObjectParameter("dkco", typeof(decimal));
    
            var cknoParameter = ckno.HasValue ?
                new ObjectParameter("ckno", ckno) :
                new ObjectParameter("ckno", typeof(decimal));
    
            var ckcoParameter = ckco.HasValue ?
                new ObjectParameter("ckco", ckco) :
                new ObjectParameter("ckco", typeof(decimal));
    
            var dkno_ntParameter = dkno_nt.HasValue ?
                new ObjectParameter("dkno_nt", dkno_nt) :
                new ObjectParameter("dkno_nt", typeof(decimal));
    
            var dkco_ntParameter = dkco_nt.HasValue ?
                new ObjectParameter("dkco_nt", dkco_nt) :
                new ObjectParameter("dkco_nt", typeof(decimal));
    
            var ckno_ntParameter = ckno_nt.HasValue ?
                new ObjectParameter("ckno_nt", ckno_nt) :
                new ObjectParameter("ckno_nt", typeof(decimal));
    
            var ckco_ntParameter = ckco_nt.HasValue ?
                new ObjectParameter("ckco_nt", ckco_nt) :
                new ObjectParameter("ckco_nt", typeof(decimal));
    
            var tableTempParameter = tableTemp != null ?
                new ObjectParameter("tableTemp", tableTemp) :
                new ObjectParameter("tableTemp", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("cn_CongNoTongHopChiTiet", maBpParameter, maHhParameter, maKhParameter, loaiNteParameter, ma_dvParameter, dknoParameter, dkcoParameter, cknoParameter, ckcoParameter, dkno_ntParameter, dkco_ntParameter, ckno_ntParameter, ckco_ntParameter, tableTempParameter);
        }
    
        public virtual int GetAllData(Nullable<System.DateTime> month)
        {
            var monthParameter = month.HasValue ?
                new ObjectParameter("month", month) :
                new ObjectParameter("month", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("GetAllData", monthParameter);
        }
    
        public virtual int hd_PhuLuc(Nullable<System.Guid> soid)
        {
            var soidParameter = soid.HasValue ?
                new ObjectParameter("soid", soid) :
                new ObjectParameter("soid", typeof(System.Guid));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("hd_PhuLuc", soidParameter);
        }
    
        public virtual int sp_alterdiagram(string diagramname, Nullable<int> owner_id, Nullable<int> version, byte[] definition)
        {
            var diagramnameParameter = diagramname != null ?
                new ObjectParameter("diagramname", diagramname) :
                new ObjectParameter("diagramname", typeof(string));
    
            var owner_idParameter = owner_id.HasValue ?
                new ObjectParameter("owner_id", owner_id) :
                new ObjectParameter("owner_id", typeof(int));
    
            var versionParameter = version.HasValue ?
                new ObjectParameter("version", version) :
                new ObjectParameter("version", typeof(int));
    
            var definitionParameter = definition != null ?
                new ObjectParameter("definition", definition) :
                new ObjectParameter("definition", typeof(byte[]));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_alterdiagram", diagramnameParameter, owner_idParameter, versionParameter, definitionParameter);
        }
    
        public virtual int sp_BaoCaoThucHienHopDong(string tableTempTT, string tableTempHD, string tableTempNT, string loaihd, string ma_cdt, string ma_kh, string ma_da, string ma_ct, Nullable<System.DateTime> tungay, Nullable<System.DateTime> denngay)
        {
            var tableTempTTParameter = tableTempTT != null ?
                new ObjectParameter("tableTempTT", tableTempTT) :
                new ObjectParameter("tableTempTT", typeof(string));
    
            var tableTempHDParameter = tableTempHD != null ?
                new ObjectParameter("tableTempHD", tableTempHD) :
                new ObjectParameter("tableTempHD", typeof(string));
    
            var tableTempNTParameter = tableTempNT != null ?
                new ObjectParameter("tableTempNT", tableTempNT) :
                new ObjectParameter("tableTempNT", typeof(string));
    
            var loaihdParameter = loaihd != null ?
                new ObjectParameter("loaihd", loaihd) :
                new ObjectParameter("loaihd", typeof(string));
    
            var ma_cdtParameter = ma_cdt != null ?
                new ObjectParameter("ma_cdt", ma_cdt) :
                new ObjectParameter("ma_cdt", typeof(string));
    
            var ma_khParameter = ma_kh != null ?
                new ObjectParameter("ma_kh", ma_kh) :
                new ObjectParameter("ma_kh", typeof(string));
    
            var ma_daParameter = ma_da != null ?
                new ObjectParameter("ma_da", ma_da) :
                new ObjectParameter("ma_da", typeof(string));
    
            var ma_ctParameter = ma_ct != null ?
                new ObjectParameter("ma_ct", ma_ct) :
                new ObjectParameter("ma_ct", typeof(string));
    
            var tungayParameter = tungay.HasValue ?
                new ObjectParameter("tungay", tungay) :
                new ObjectParameter("tungay", typeof(System.DateTime));
    
            var denngayParameter = denngay.HasValue ?
                new ObjectParameter("denngay", denngay) :
                new ObjectParameter("denngay", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_BaoCaoThucHienHopDong", tableTempTTParameter, tableTempHDParameter, tableTempNTParameter, loaihdParameter, ma_cdtParameter, ma_khParameter, ma_daParameter, ma_ctParameter, tungayParameter, denngayParameter);
        }
    
        public virtual int sp_BaoCaoThucHienHopDongCT(string tableTempTT, string tableTempHD, string tableTempNT, Nullable<System.DateTime> tungay, Nullable<System.DateTime> denngay)
        {
            var tableTempTTParameter = tableTempTT != null ?
                new ObjectParameter("tableTempTT", tableTempTT) :
                new ObjectParameter("tableTempTT", typeof(string));
    
            var tableTempHDParameter = tableTempHD != null ?
                new ObjectParameter("tableTempHD", tableTempHD) :
                new ObjectParameter("tableTempHD", typeof(string));
    
            var tableTempNTParameter = tableTempNT != null ?
                new ObjectParameter("tableTempNT", tableTempNT) :
                new ObjectParameter("tableTempNT", typeof(string));
    
            var tungayParameter = tungay.HasValue ?
                new ObjectParameter("tungay", tungay) :
                new ObjectParameter("tungay", typeof(System.DateTime));
    
            var denngayParameter = denngay.HasValue ?
                new ObjectParameter("denngay", denngay) :
                new ObjectParameter("denngay", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_BaoCaoThucHienHopDongCT", tableTempTTParameter, tableTempHDParameter, tableTempNTParameter, tungayParameter, denngayParameter);
        }
    
        public virtual int sp_BaoCaoThucHienHopDongMua(string tableTempTT, string tableTempHD, string tableTempNT, Nullable<System.DateTime> tungay, Nullable<System.DateTime> denngay)
        {
            var tableTempTTParameter = tableTempTT != null ?
                new ObjectParameter("tableTempTT", tableTempTT) :
                new ObjectParameter("tableTempTT", typeof(string));
    
            var tableTempHDParameter = tableTempHD != null ?
                new ObjectParameter("tableTempHD", tableTempHD) :
                new ObjectParameter("tableTempHD", typeof(string));
    
            var tableTempNTParameter = tableTempNT != null ?
                new ObjectParameter("tableTempNT", tableTempNT) :
                new ObjectParameter("tableTempNT", typeof(string));
    
            var tungayParameter = tungay.HasValue ?
                new ObjectParameter("tungay", tungay) :
                new ObjectParameter("tungay", typeof(System.DateTime));
    
            var denngayParameter = denngay.HasValue ?
                new ObjectParameter("denngay", denngay) :
                new ObjectParameter("denngay", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_BaoCaoThucHienHopDongMua", tableTempTTParameter, tableTempHDParameter, tableTempNTParameter, tungayParameter, denngayParameter);
        }
    
        public virtual int sp_BaoCaoThucHienHopDongMuaCT(string tableTempTT, string tableTempHD, string tableTempNT, Nullable<System.DateTime> tungay, Nullable<System.DateTime> denngay)
        {
            var tableTempTTParameter = tableTempTT != null ?
                new ObjectParameter("tableTempTT", tableTempTT) :
                new ObjectParameter("tableTempTT", typeof(string));
    
            var tableTempHDParameter = tableTempHD != null ?
                new ObjectParameter("tableTempHD", tableTempHD) :
                new ObjectParameter("tableTempHD", typeof(string));
    
            var tableTempNTParameter = tableTempNT != null ?
                new ObjectParameter("tableTempNT", tableTempNT) :
                new ObjectParameter("tableTempNT", typeof(string));
    
            var tungayParameter = tungay.HasValue ?
                new ObjectParameter("tungay", tungay) :
                new ObjectParameter("tungay", typeof(System.DateTime));
    
            var denngayParameter = denngay.HasValue ?
                new ObjectParameter("denngay", denngay) :
                new ObjectParameter("denngay", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_BaoCaoThucHienHopDongMuaCT", tableTempTTParameter, tableTempHDParameter, tableTempNTParameter, tungayParameter, denngayParameter);
        }
    
        public virtual int sp_CapNhapDetail(Nullable<System.Guid> id, Nullable<System.Guid> soid, string tentaptin, string driveid, Nullable<int> sott)
        {
            var idParameter = id.HasValue ?
                new ObjectParameter("id", id) :
                new ObjectParameter("id", typeof(System.Guid));
    
            var soidParameter = soid.HasValue ?
                new ObjectParameter("soid", soid) :
                new ObjectParameter("soid", typeof(System.Guid));
    
            var tentaptinParameter = tentaptin != null ?
                new ObjectParameter("tentaptin", tentaptin) :
                new ObjectParameter("tentaptin", typeof(string));
    
            var driveidParameter = driveid != null ?
                new ObjectParameter("driveid", driveid) :
                new ObjectParameter("driveid", typeof(string));
    
            var sottParameter = sott.HasValue ?
                new ObjectParameter("sott", sott) :
                new ObjectParameter("sott", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_CapNhapDetail", idParameter, soidParameter, tentaptinParameter, driveidParameter, sottParameter);
        }
    
        public virtual int sp_CapNhapMaster(Nullable<System.Guid> soid, string dinhdanh, string ma_tieuchi, string nguoitao, Nullable<System.DateTime> ngaytao)
        {
            var soidParameter = soid.HasValue ?
                new ObjectParameter("soid", soid) :
                new ObjectParameter("soid", typeof(System.Guid));
    
            var dinhdanhParameter = dinhdanh != null ?
                new ObjectParameter("dinhdanh", dinhdanh) :
                new ObjectParameter("dinhdanh", typeof(string));
    
            var ma_tieuchiParameter = ma_tieuchi != null ?
                new ObjectParameter("ma_tieuchi", ma_tieuchi) :
                new ObjectParameter("ma_tieuchi", typeof(string));
    
            var nguoitaoParameter = nguoitao != null ?
                new ObjectParameter("nguoitao", nguoitao) :
                new ObjectParameter("nguoitao", typeof(string));
    
            var ngaytaoParameter = ngaytao.HasValue ?
                new ObjectParameter("ngaytao", ngaytao) :
                new ObjectParameter("ngaytao", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_CapNhapMaster", soidParameter, dinhdanhParameter, ma_tieuchiParameter, nguoitaoParameter, ngaytaoParameter);
        }
    
        public virtual int sp_CapNhatQLNguoiDung(Nullable<System.Guid> id, string ma_nsd, string ten_nsd, string matkhau, string makhoa, string mabomon, string ma_nhom, string ghichu, string nguoisua, Nullable<System.DateTime> ngaysua)
        {
            var idParameter = id.HasValue ?
                new ObjectParameter("id", id) :
                new ObjectParameter("id", typeof(System.Guid));
    
            var ma_nsdParameter = ma_nsd != null ?
                new ObjectParameter("ma_nsd", ma_nsd) :
                new ObjectParameter("ma_nsd", typeof(string));
    
            var ten_nsdParameter = ten_nsd != null ?
                new ObjectParameter("ten_nsd", ten_nsd) :
                new ObjectParameter("ten_nsd", typeof(string));
    
            var matkhauParameter = matkhau != null ?
                new ObjectParameter("matkhau", matkhau) :
                new ObjectParameter("matkhau", typeof(string));
    
            var makhoaParameter = makhoa != null ?
                new ObjectParameter("makhoa", makhoa) :
                new ObjectParameter("makhoa", typeof(string));
    
            var mabomonParameter = mabomon != null ?
                new ObjectParameter("mabomon", mabomon) :
                new ObjectParameter("mabomon", typeof(string));
    
            var ma_nhomParameter = ma_nhom != null ?
                new ObjectParameter("ma_nhom", ma_nhom) :
                new ObjectParameter("ma_nhom", typeof(string));
    
            var ghichuParameter = ghichu != null ?
                new ObjectParameter("ghichu", ghichu) :
                new ObjectParameter("ghichu", typeof(string));
    
            var nguoisuaParameter = nguoisua != null ?
                new ObjectParameter("nguoisua", nguoisua) :
                new ObjectParameter("nguoisua", typeof(string));
    
            var ngaysuaParameter = ngaysua.HasValue ?
                new ObjectParameter("ngaysua", ngaysua) :
                new ObjectParameter("ngaysua", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_CapNhatQLNguoiDung", idParameter, ma_nsdParameter, ten_nsdParameter, matkhauParameter, makhoaParameter, mabomonParameter, ma_nhomParameter, ghichuParameter, nguoisuaParameter, ngaysuaParameter);
        }
    
        public virtual int sp_CapNhatThongTinBM(Nullable<System.Guid> id, string mabomon, string tenbomon, string makhoa, string googledrive)
        {
            var idParameter = id.HasValue ?
                new ObjectParameter("id", id) :
                new ObjectParameter("id", typeof(System.Guid));
    
            var mabomonParameter = mabomon != null ?
                new ObjectParameter("mabomon", mabomon) :
                new ObjectParameter("mabomon", typeof(string));
    
            var tenbomonParameter = tenbomon != null ?
                new ObjectParameter("tenbomon", tenbomon) :
                new ObjectParameter("tenbomon", typeof(string));
    
            var makhoaParameter = makhoa != null ?
                new ObjectParameter("makhoa", makhoa) :
                new ObjectParameter("makhoa", typeof(string));
    
            var googledriveParameter = googledrive != null ?
                new ObjectParameter("googledrive", googledrive) :
                new ObjectParameter("googledrive", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_CapNhatThongTinBM", idParameter, mabomonParameter, tenbomonParameter, makhoaParameter, googledriveParameter);
        }
    
        public virtual int sp_CapNhatThongTinKhoa(Nullable<System.Guid> id, string makhoa, string tenkhoa)
        {
            var idParameter = id.HasValue ?
                new ObjectParameter("id", id) :
                new ObjectParameter("id", typeof(System.Guid));
    
            var makhoaParameter = makhoa != null ?
                new ObjectParameter("makhoa", makhoa) :
                new ObjectParameter("makhoa", typeof(string));
    
            var tenkhoaParameter = tenkhoa != null ?
                new ObjectParameter("tenkhoa", tenkhoa) :
                new ObjectParameter("tenkhoa", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_CapNhatThongTinKhoa", idParameter, makhoaParameter, tenkhoaParameter);
        }
    
        public virtual int sp_CapNhatTieuChi(Nullable<System.Guid> id, string ma_tieuchi, string ten_tieuchi, string ma_tieuchuan, string nguoisua, Nullable<System.DateTime> ngaysua, string noidung)
        {
            var idParameter = id.HasValue ?
                new ObjectParameter("id", id) :
                new ObjectParameter("id", typeof(System.Guid));
    
            var ma_tieuchiParameter = ma_tieuchi != null ?
                new ObjectParameter("ma_tieuchi", ma_tieuchi) :
                new ObjectParameter("ma_tieuchi", typeof(string));
    
            var ten_tieuchiParameter = ten_tieuchi != null ?
                new ObjectParameter("ten_tieuchi", ten_tieuchi) :
                new ObjectParameter("ten_tieuchi", typeof(string));
    
            var ma_tieuchuanParameter = ma_tieuchuan != null ?
                new ObjectParameter("ma_tieuchuan", ma_tieuchuan) :
                new ObjectParameter("ma_tieuchuan", typeof(string));
    
            var nguoisuaParameter = nguoisua != null ?
                new ObjectParameter("nguoisua", nguoisua) :
                new ObjectParameter("nguoisua", typeof(string));
    
            var ngaysuaParameter = ngaysua.HasValue ?
                new ObjectParameter("ngaysua", ngaysua) :
                new ObjectParameter("ngaysua", typeof(System.DateTime));
    
            var noidungParameter = noidung != null ?
                new ObjectParameter("noidung", noidung) :
                new ObjectParameter("noidung", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_CapNhatTieuChi", idParameter, ma_tieuchiParameter, ten_tieuchiParameter, ma_tieuchuanParameter, nguoisuaParameter, ngaysuaParameter, noidungParameter);
        }
    
        public virtual int sp_CapNhatTieuChuan(Nullable<System.Guid> id, string ma_tieuchuan, string ten_tieuchuan, string nguoisua, Nullable<System.DateTime> ngaysua, string noidung)
        {
            var idParameter = id.HasValue ?
                new ObjectParameter("id", id) :
                new ObjectParameter("id", typeof(System.Guid));
    
            var ma_tieuchuanParameter = ma_tieuchuan != null ?
                new ObjectParameter("ma_tieuchuan", ma_tieuchuan) :
                new ObjectParameter("ma_tieuchuan", typeof(string));
    
            var ten_tieuchuanParameter = ten_tieuchuan != null ?
                new ObjectParameter("ten_tieuchuan", ten_tieuchuan) :
                new ObjectParameter("ten_tieuchuan", typeof(string));
    
            var nguoisuaParameter = nguoisua != null ?
                new ObjectParameter("nguoisua", nguoisua) :
                new ObjectParameter("nguoisua", typeof(string));
    
            var ngaysuaParameter = ngaysua.HasValue ?
                new ObjectParameter("ngaysua", ngaysua) :
                new ObjectParameter("ngaysua", typeof(System.DateTime));
    
            var noidungParameter = noidung != null ?
                new ObjectParameter("noidung", noidung) :
                new ObjectParameter("noidung", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_CapNhatTieuChuan", idParameter, ma_tieuchuanParameter, ten_tieuchuanParameter, nguoisuaParameter, ngaysuaParameter, noidungParameter);
        }
    
        public virtual int sp_creatediagram(string diagramname, Nullable<int> owner_id, Nullable<int> version, byte[] definition)
        {
            var diagramnameParameter = diagramname != null ?
                new ObjectParameter("diagramname", diagramname) :
                new ObjectParameter("diagramname", typeof(string));
    
            var owner_idParameter = owner_id.HasValue ?
                new ObjectParameter("owner_id", owner_id) :
                new ObjectParameter("owner_id", typeof(int));
    
            var versionParameter = version.HasValue ?
                new ObjectParameter("version", version) :
                new ObjectParameter("version", typeof(int));
    
            var definitionParameter = definition != null ?
                new ObjectParameter("definition", definition) :
                new ObjectParameter("definition", typeof(byte[]));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_creatediagram", diagramnameParameter, owner_idParameter, versionParameter, definitionParameter);
        }
    
        public virtual int sp_DanhSachCanBoCongChucVienChucNLD()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_DanhSachCanBoCongChucVienChucNLD");
        }
    
        public virtual int sp_DanhSachLuongPhuCapNhanVien(Nullable<decimal> luongcoban)
        {
            var luongcobanParameter = luongcoban.HasValue ?
                new ObjectParameter("luongcoban", luongcoban) :
                new ObjectParameter("luongcoban", typeof(decimal));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_DanhSachLuongPhuCapNhanVien", luongcobanParameter);
        }
    
        public virtual int sp_DanhSachNghiemThuTongHop()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_DanhSachNghiemThuTongHop");
        }
    
        public virtual int sp_DanhSachNhanVienDiNuocNgoai(Nullable<System.DateTime> denngay)
        {
            var denngayParameter = denngay.HasValue ?
                new ObjectParameter("denngay", denngay) :
                new ObjectParameter("denngay", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_DanhSachNhanVienDiNuocNgoai", denngayParameter);
        }
    
        public virtual int sp_DanhSachNhanVienKhenThuong(Nullable<System.DateTime> tungay, Nullable<System.DateTime> denngay)
        {
            var tungayParameter = tungay.HasValue ?
                new ObjectParameter("tungay", tungay) :
                new ObjectParameter("tungay", typeof(System.DateTime));
    
            var denngayParameter = denngay.HasValue ?
                new ObjectParameter("denngay", denngay) :
                new ObjectParameter("denngay", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_DanhSachNhanVienKhenThuong", tungayParameter, denngayParameter);
        }
    
        public virtual int sp_DanhSachNhanVienKyLuat(Nullable<System.DateTime> tungay, Nullable<System.DateTime> denngay)
        {
            var tungayParameter = tungay.HasValue ?
                new ObjectParameter("tungay", tungay) :
                new ObjectParameter("tungay", typeof(System.DateTime));
    
            var denngayParameter = denngay.HasValue ?
                new ObjectParameter("denngay", denngay) :
                new ObjectParameter("denngay", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_DanhSachNhanVienKyLuat", tungayParameter, denngayParameter);
        }
    
        public virtual int sp_DanhSachNhanVienNghiPhep(Nullable<System.DateTime> tungay, Nullable<System.DateTime> denngay, string ma_nv)
        {
            var tungayParameter = tungay.HasValue ?
                new ObjectParameter("tungay", tungay) :
                new ObjectParameter("tungay", typeof(System.DateTime));
    
            var denngayParameter = denngay.HasValue ?
                new ObjectParameter("denngay", denngay) :
                new ObjectParameter("denngay", typeof(System.DateTime));
    
            var ma_nvParameter = ma_nv != null ?
                new ObjectParameter("ma_nv", ma_nv) :
                new ObjectParameter("ma_nv", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_DanhSachNhanVienNghiPhep", tungayParameter, denngayParameter, ma_nvParameter);
        }
    
        public virtual int sp_DanhSachNhanVienThamGiaBaoHiem()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_DanhSachNhanVienThamGiaBaoHiem");
        }
    
        public virtual int sp_DanhSachNhanVienThamGiaDaoTao(Nullable<System.DateTime> tungay, Nullable<System.DateTime> denngay)
        {
            var tungayParameter = tungay.HasValue ?
                new ObjectParameter("tungay", tungay) :
                new ObjectParameter("tungay", typeof(System.DateTime));
    
            var denngayParameter = denngay.HasValue ?
                new ObjectParameter("denngay", denngay) :
                new ObjectParameter("denngay", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_DanhSachNhanVienThamGiaDaoTao", tungayParameter, denngayParameter);
        }
    
        public virtual int sp_DanhSachNhanVienTheoPhongBan()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_DanhSachNhanVienTheoPhongBan");
        }
    
        public virtual int sp_dropdiagram(string diagramname, Nullable<int> owner_id)
        {
            var diagramnameParameter = diagramname != null ?
                new ObjectParameter("diagramname", diagramname) :
                new ObjectParameter("diagramname", typeof(string));
    
            var owner_idParameter = owner_id.HasValue ?
                new ObjectParameter("owner_id", owner_id) :
                new ObjectParameter("owner_id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_dropdiagram", diagramnameParameter, owner_idParameter);
        }
    
        public virtual ObjectResult<sp_helpdiagramdefinition_Result> sp_helpdiagramdefinition(string diagramname, Nullable<int> owner_id)
        {
            var diagramnameParameter = diagramname != null ?
                new ObjectParameter("diagramname", diagramname) :
                new ObjectParameter("diagramname", typeof(string));
    
            var owner_idParameter = owner_id.HasValue ?
                new ObjectParameter("owner_id", owner_id) :
                new ObjectParameter("owner_id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_helpdiagramdefinition_Result>("sp_helpdiagramdefinition", diagramnameParameter, owner_idParameter);
        }
    
        public virtual ObjectResult<sp_helpdiagrams_Result> sp_helpdiagrams(string diagramname, Nullable<int> owner_id)
        {
            var diagramnameParameter = diagramname != null ?
                new ObjectParameter("diagramname", diagramname) :
                new ObjectParameter("diagramname", typeof(string));
    
            var owner_idParameter = owner_id.HasValue ?
                new ObjectParameter("owner_id", owner_id) :
                new ObjectParameter("owner_id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_helpdiagrams_Result>("sp_helpdiagrams", diagramnameParameter, owner_idParameter);
        }
    
        public virtual int sp_LayDuLieu()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_LayDuLieu");
        }
    
        public virtual int sp_renamediagram(string diagramname, Nullable<int> owner_id, string new_diagramname)
        {
            var diagramnameParameter = diagramname != null ?
                new ObjectParameter("diagramname", diagramname) :
                new ObjectParameter("diagramname", typeof(string));
    
            var owner_idParameter = owner_id.HasValue ?
                new ObjectParameter("owner_id", owner_id) :
                new ObjectParameter("owner_id", typeof(int));
    
            var new_diagramnameParameter = new_diagramname != null ?
                new ObjectParameter("new_diagramname", new_diagramname) :
                new ObjectParameter("new_diagramname", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_renamediagram", diagramnameParameter, owner_idParameter, new_diagramnameParameter);
        }
    
        public virtual int sp_ThemMoiQLNguoiDung(Nullable<System.Guid> id, string ma_nsd, string ten_nsd, string matkhau, string makhoa, string mabomon, string ma_nhom, string ghichu, string nguoitao, Nullable<System.DateTime> ngaytao)
        {
            var idParameter = id.HasValue ?
                new ObjectParameter("id", id) :
                new ObjectParameter("id", typeof(System.Guid));
    
            var ma_nsdParameter = ma_nsd != null ?
                new ObjectParameter("ma_nsd", ma_nsd) :
                new ObjectParameter("ma_nsd", typeof(string));
    
            var ten_nsdParameter = ten_nsd != null ?
                new ObjectParameter("ten_nsd", ten_nsd) :
                new ObjectParameter("ten_nsd", typeof(string));
    
            var matkhauParameter = matkhau != null ?
                new ObjectParameter("matkhau", matkhau) :
                new ObjectParameter("matkhau", typeof(string));
    
            var makhoaParameter = makhoa != null ?
                new ObjectParameter("makhoa", makhoa) :
                new ObjectParameter("makhoa", typeof(string));
    
            var mabomonParameter = mabomon != null ?
                new ObjectParameter("mabomon", mabomon) :
                new ObjectParameter("mabomon", typeof(string));
    
            var ma_nhomParameter = ma_nhom != null ?
                new ObjectParameter("ma_nhom", ma_nhom) :
                new ObjectParameter("ma_nhom", typeof(string));
    
            var ghichuParameter = ghichu != null ?
                new ObjectParameter("ghichu", ghichu) :
                new ObjectParameter("ghichu", typeof(string));
    
            var nguoitaoParameter = nguoitao != null ?
                new ObjectParameter("nguoitao", nguoitao) :
                new ObjectParameter("nguoitao", typeof(string));
    
            var ngaytaoParameter = ngaytao.HasValue ?
                new ObjectParameter("ngaytao", ngaytao) :
                new ObjectParameter("ngaytao", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_ThemMoiQLNguoiDung", idParameter, ma_nsdParameter, ten_nsdParameter, matkhauParameter, makhoaParameter, mabomonParameter, ma_nhomParameter, ghichuParameter, nguoitaoParameter, ngaytaoParameter);
        }
    
        public virtual int sp_ThemMoiThongTinBM(Nullable<System.Guid> id, string mabomon, string tenbomon, string makhoa, string googledrive)
        {
            var idParameter = id.HasValue ?
                new ObjectParameter("id", id) :
                new ObjectParameter("id", typeof(System.Guid));
    
            var mabomonParameter = mabomon != null ?
                new ObjectParameter("mabomon", mabomon) :
                new ObjectParameter("mabomon", typeof(string));
    
            var tenbomonParameter = tenbomon != null ?
                new ObjectParameter("tenbomon", tenbomon) :
                new ObjectParameter("tenbomon", typeof(string));
    
            var makhoaParameter = makhoa != null ?
                new ObjectParameter("makhoa", makhoa) :
                new ObjectParameter("makhoa", typeof(string));
    
            var googledriveParameter = googledrive != null ?
                new ObjectParameter("googledrive", googledrive) :
                new ObjectParameter("googledrive", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_ThemMoiThongTinBM", idParameter, mabomonParameter, tenbomonParameter, makhoaParameter, googledriveParameter);
        }
    
        public virtual int sp_ThemMoiThongTinKhoa(Nullable<System.Guid> id, string makhoa, string tenkhoa)
        {
            var idParameter = id.HasValue ?
                new ObjectParameter("id", id) :
                new ObjectParameter("id", typeof(System.Guid));
    
            var makhoaParameter = makhoa != null ?
                new ObjectParameter("makhoa", makhoa) :
                new ObjectParameter("makhoa", typeof(string));
    
            var tenkhoaParameter = tenkhoa != null ?
                new ObjectParameter("tenkhoa", tenkhoa) :
                new ObjectParameter("tenkhoa", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_ThemMoiThongTinKhoa", idParameter, makhoaParameter, tenkhoaParameter);
        }
    
        public virtual int sp_ThemMoiTieuChi(Nullable<System.Guid> id, string ma_tieuchi, string ten_tieuchi, string ma_tieuchuan, string nguoitao, Nullable<System.DateTime> ngaytao, string noidung)
        {
            var idParameter = id.HasValue ?
                new ObjectParameter("id", id) :
                new ObjectParameter("id", typeof(System.Guid));
    
            var ma_tieuchiParameter = ma_tieuchi != null ?
                new ObjectParameter("ma_tieuchi", ma_tieuchi) :
                new ObjectParameter("ma_tieuchi", typeof(string));
    
            var ten_tieuchiParameter = ten_tieuchi != null ?
                new ObjectParameter("ten_tieuchi", ten_tieuchi) :
                new ObjectParameter("ten_tieuchi", typeof(string));
    
            var ma_tieuchuanParameter = ma_tieuchuan != null ?
                new ObjectParameter("ma_tieuchuan", ma_tieuchuan) :
                new ObjectParameter("ma_tieuchuan", typeof(string));
    
            var nguoitaoParameter = nguoitao != null ?
                new ObjectParameter("nguoitao", nguoitao) :
                new ObjectParameter("nguoitao", typeof(string));
    
            var ngaytaoParameter = ngaytao.HasValue ?
                new ObjectParameter("ngaytao", ngaytao) :
                new ObjectParameter("ngaytao", typeof(System.DateTime));
    
            var noidungParameter = noidung != null ?
                new ObjectParameter("noidung", noidung) :
                new ObjectParameter("noidung", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_ThemMoiTieuChi", idParameter, ma_tieuchiParameter, ten_tieuchiParameter, ma_tieuchuanParameter, nguoitaoParameter, ngaytaoParameter, noidungParameter);
        }
    
        public virtual int sp_ThemMoiTieuChuan(Nullable<System.Guid> id, string ma_tieuchuan, string ten_tieuchuan, string nguoitao, Nullable<System.DateTime> ngaytao, string noidung)
        {
            var idParameter = id.HasValue ?
                new ObjectParameter("id", id) :
                new ObjectParameter("id", typeof(System.Guid));
    
            var ma_tieuchuanParameter = ma_tieuchuan != null ?
                new ObjectParameter("ma_tieuchuan", ma_tieuchuan) :
                new ObjectParameter("ma_tieuchuan", typeof(string));
    
            var ten_tieuchuanParameter = ten_tieuchuan != null ?
                new ObjectParameter("ten_tieuchuan", ten_tieuchuan) :
                new ObjectParameter("ten_tieuchuan", typeof(string));
    
            var nguoitaoParameter = nguoitao != null ?
                new ObjectParameter("nguoitao", nguoitao) :
                new ObjectParameter("nguoitao", typeof(string));
    
            var ngaytaoParameter = ngaytao.HasValue ?
                new ObjectParameter("ngaytao", ngaytao) :
                new ObjectParameter("ngaytao", typeof(System.DateTime));
    
            var noidungParameter = noidung != null ?
                new ObjectParameter("noidung", noidung) :
                new ObjectParameter("noidung", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_ThemMoiTieuChuan", idParameter, ma_tieuchuanParameter, ten_tieuchuanParameter, nguoitaoParameter, ngaytaoParameter, noidungParameter);
        }
    
        public virtual int sp_ThongKeNgayNghiPhepCuaNhanVien(Nullable<System.DateTime> tungay, Nullable<System.DateTime> denngay)
        {
            var tungayParameter = tungay.HasValue ?
                new ObjectParameter("tungay", tungay) :
                new ObjectParameter("tungay", typeof(System.DateTime));
    
            var denngayParameter = denngay.HasValue ?
                new ObjectParameter("denngay", denngay) :
                new ObjectParameter("denngay", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_ThongKeNgayNghiPhepCuaNhanVien", tungayParameter, denngayParameter);
        }
    
        public virtual int sp_upgraddiagrams()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_upgraddiagrams");
        }
    
        public virtual ObjectResult<spDanhMucPhanQuyen_Result> spDanhMucPhanQuyen(string ma_nsd)
        {
            var ma_nsdParameter = ma_nsd != null ?
                new ObjectParameter("ma_nsd", ma_nsd) :
                new ObjectParameter("ma_nsd", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<spDanhMucPhanQuyen_Result>("spDanhMucPhanQuyen", ma_nsdParameter);
        }
    
        public virtual ObjectResult<spPhanQuyenNguoiDung_Result> spPhanQuyenNguoiDung(string ma_nsd)
        {
            var ma_nsdParameter = ma_nsd != null ?
                new ObjectParameter("ma_nsd", ma_nsd) :
                new ObjectParameter("ma_nsd", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<spPhanQuyenNguoiDung_Result>("spPhanQuyenNguoiDung", ma_nsdParameter);
        }
    
        public virtual int tc_SoQuy(string matk, Nullable<System.DateTime> tungay, Nullable<System.DateTime> denngay, Nullable<bool> noibo, string ma_nsd)
        {
            var matkParameter = matk != null ?
                new ObjectParameter("matk", matk) :
                new ObjectParameter("matk", typeof(string));
    
            var tungayParameter = tungay.HasValue ?
                new ObjectParameter("tungay", tungay) :
                new ObjectParameter("tungay", typeof(System.DateTime));
    
            var denngayParameter = denngay.HasValue ?
                new ObjectParameter("denngay", denngay) :
                new ObjectParameter("denngay", typeof(System.DateTime));
    
            var noiboParameter = noibo.HasValue ?
                new ObjectParameter("noibo", noibo) :
                new ObjectParameter("noibo", typeof(bool));
    
            var ma_nsdParameter = ma_nsd != null ?
                new ObjectParameter("ma_nsd", ma_nsd) :
                new ObjectParameter("ma_nsd", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("tc_SoQuy", matkParameter, tungayParameter, denngayParameter, noiboParameter, ma_nsdParameter);
        }
    
        public virtual int th_BaoCaoChiTietTheoNganHang(string tempTable, Nullable<System.DateTime> tuNgay, Nullable<System.DateTime> denNgay, Nullable<bool> loai, string ma_nsd)
        {
            var tempTableParameter = tempTable != null ?
                new ObjectParameter("tempTable", tempTable) :
                new ObjectParameter("tempTable", typeof(string));
    
            var tuNgayParameter = tuNgay.HasValue ?
                new ObjectParameter("tuNgay", tuNgay) :
                new ObjectParameter("tuNgay", typeof(System.DateTime));
    
            var denNgayParameter = denNgay.HasValue ?
                new ObjectParameter("denNgay", denNgay) :
                new ObjectParameter("denNgay", typeof(System.DateTime));
    
            var loaiParameter = loai.HasValue ?
                new ObjectParameter("loai", loai) :
                new ObjectParameter("loai", typeof(bool));
    
            var ma_nsdParameter = ma_nsd != null ?
                new ObjectParameter("ma_nsd", ma_nsd) :
                new ObjectParameter("ma_nsd", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("th_BaoCaoChiTietTheoNganHang", tempTableParameter, tuNgayParameter, denNgayParameter, loaiParameter, ma_nsdParameter);
        }
    
        public virtual int th_BaoCaoQuanLyTaiSan(Nullable<System.DateTime> tuNgay, Nullable<System.DateTime> denNgay)
        {
            var tuNgayParameter = tuNgay.HasValue ?
                new ObjectParameter("tuNgay", tuNgay) :
                new ObjectParameter("tuNgay", typeof(System.DateTime));
    
            var denNgayParameter = denNgay.HasValue ?
                new ObjectParameter("denNgay", denNgay) :
                new ObjectParameter("denNgay", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("th_BaoCaoQuanLyTaiSan", tuNgayParameter, denNgayParameter);
        }
    
        public virtual int th_CanDoiPhatSinh(Nullable<System.DateTime> tungay, Nullable<System.DateTime> denngay, string tableTemp, Nullable<bool> loai, Nullable<bool> noibo)
        {
            var tungayParameter = tungay.HasValue ?
                new ObjectParameter("tungay", tungay) :
                new ObjectParameter("tungay", typeof(System.DateTime));
    
            var denngayParameter = denngay.HasValue ?
                new ObjectParameter("denngay", denngay) :
                new ObjectParameter("denngay", typeof(System.DateTime));
    
            var tableTempParameter = tableTemp != null ?
                new ObjectParameter("tableTemp", tableTemp) :
                new ObjectParameter("tableTemp", typeof(string));
    
            var loaiParameter = loai.HasValue ?
                new ObjectParameter("loai", loai) :
                new ObjectParameter("loai", typeof(bool));
    
            var noiboParameter = noibo.HasValue ?
                new ObjectParameter("noibo", noibo) :
                new ObjectParameter("noibo", typeof(bool));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("th_CanDoiPhatSinh", tungayParameter, denngayParameter, tableTempParameter, loaiParameter, noiboParameter);
        }
    
        public virtual int th_SoChiTiet(Nullable<System.DateTime> tuNgay, Nullable<System.DateTime> denNgay, string maTK, Nullable<bool> noibo, Nullable<bool> loai, string ma_nsd)
        {
            var tuNgayParameter = tuNgay.HasValue ?
                new ObjectParameter("tuNgay", tuNgay) :
                new ObjectParameter("tuNgay", typeof(System.DateTime));
    
            var denNgayParameter = denNgay.HasValue ?
                new ObjectParameter("denNgay", denNgay) :
                new ObjectParameter("denNgay", typeof(System.DateTime));
    
            var maTKParameter = maTK != null ?
                new ObjectParameter("maTK", maTK) :
                new ObjectParameter("maTK", typeof(string));
    
            var noiboParameter = noibo.HasValue ?
                new ObjectParameter("noibo", noibo) :
                new ObjectParameter("noibo", typeof(bool));
    
            var loaiParameter = loai.HasValue ?
                new ObjectParameter("loai", loai) :
                new ObjectParameter("loai", typeof(bool));
    
            var ma_nsdParameter = ma_nsd != null ?
                new ObjectParameter("ma_nsd", ma_nsd) :
                new ObjectParameter("ma_nsd", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("th_SoChiTiet", tuNgayParameter, denNgayParameter, maTKParameter, noiboParameter, loaiParameter, ma_nsdParameter);
        }
    
        public virtual int th_TongHopChiPhiTheoBoPhan(string tempTable, Nullable<System.DateTime> tuNgay, Nullable<System.DateTime> denNgay)
        {
            var tempTableParameter = tempTable != null ?
                new ObjectParameter("tempTable", tempTable) :
                new ObjectParameter("tempTable", typeof(string));
    
            var tuNgayParameter = tuNgay.HasValue ?
                new ObjectParameter("tuNgay", tuNgay) :
                new ObjectParameter("tuNgay", typeof(System.DateTime));
    
            var denNgayParameter = denNgay.HasValue ?
                new ObjectParameter("denNgay", denNgay) :
                new ObjectParameter("denNgay", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("th_TongHopChiPhiTheoBoPhan", tempTableParameter, tuNgayParameter, denNgayParameter);
        }
    
        public virtual int sp_CapNhatND(Nullable<System.Guid> id, string ma_tieuchi, string ten_tieuchi, string nguoisua, Nullable<System.DateTime> ngaysua, string noidung)
        {
            var idParameter = id.HasValue ?
                new ObjectParameter("id", id) :
                new ObjectParameter("id", typeof(System.Guid));
    
            var ma_tieuchiParameter = ma_tieuchi != null ?
                new ObjectParameter("ma_tieuchi", ma_tieuchi) :
                new ObjectParameter("ma_tieuchi", typeof(string));
    
            var ten_tieuchiParameter = ten_tieuchi != null ?
                new ObjectParameter("ten_tieuchi", ten_tieuchi) :
                new ObjectParameter("ten_tieuchi", typeof(string));
    
            var nguoisuaParameter = nguoisua != null ?
                new ObjectParameter("nguoisua", nguoisua) :
                new ObjectParameter("nguoisua", typeof(string));
    
            var ngaysuaParameter = ngaysua.HasValue ?
                new ObjectParameter("ngaysua", ngaysua) :
                new ObjectParameter("ngaysua", typeof(System.DateTime));
    
            var noidungParameter = noidung != null ?
                new ObjectParameter("noidung", noidung) :
                new ObjectParameter("noidung", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_CapNhatND", idParameter, ma_tieuchiParameter, ten_tieuchiParameter, nguoisuaParameter, ngaysuaParameter, noidungParameter);
        }
    
        public virtual int sp_ThemMoiND(Nullable<System.Guid> id, string ma_tieuchi, string ten_tieuchi, string nguoitao, Nullable<System.DateTime> ngaytao, string noidung)
        {
            var idParameter = id.HasValue ?
                new ObjectParameter("id", id) :
                new ObjectParameter("id", typeof(System.Guid));
    
            var ma_tieuchiParameter = ma_tieuchi != null ?
                new ObjectParameter("ma_tieuchi", ma_tieuchi) :
                new ObjectParameter("ma_tieuchi", typeof(string));
    
            var ten_tieuchiParameter = ten_tieuchi != null ?
                new ObjectParameter("ten_tieuchi", ten_tieuchi) :
                new ObjectParameter("ten_tieuchi", typeof(string));
    
            var nguoitaoParameter = nguoitao != null ?
                new ObjectParameter("nguoitao", nguoitao) :
                new ObjectParameter("nguoitao", typeof(string));
    
            var ngaytaoParameter = ngaytao.HasValue ?
                new ObjectParameter("ngaytao", ngaytao) :
                new ObjectParameter("ngaytao", typeof(System.DateTime));
    
            var noidungParameter = noidung != null ?
                new ObjectParameter("noidung", noidung) :
                new ObjectParameter("noidung", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_ThemMoiND", idParameter, ma_tieuchiParameter, ten_tieuchiParameter, nguoitaoParameter, ngaytaoParameter, noidungParameter);
        }
    
        public virtual ObjectResult<sp_DanhSachTaiLieu_Result> sp_DanhSachTaiLieu(string dinhdanh, string ma_tieuchi)
        {
            var dinhdanhParameter = dinhdanh != null ?
                new ObjectParameter("dinhdanh", dinhdanh) :
                new ObjectParameter("dinhdanh", typeof(string));
    
            var ma_tieuchiParameter = ma_tieuchi != null ?
                new ObjectParameter("ma_tieuchi", ma_tieuchi) :
                new ObjectParameter("ma_tieuchi", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_DanhSachTaiLieu_Result>("sp_DanhSachTaiLieu", dinhdanhParameter, ma_tieuchiParameter);
        }
    
        public virtual ObjectResult<sp_DuLieuChiTiet_Result> sp_DuLieuChiTiet()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_DuLieuChiTiet_Result>("sp_DuLieuChiTiet");
        }
    
        public virtual ObjectResult<sp_DuLieuGoc_Result> sp_DuLieuGoc()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_DuLieuGoc_Result>("sp_DuLieuGoc");
        }
    }
}
